apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  labels:
    app: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: registry.digitalocean.com/ecommerce2022/ecommerce:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: testapp-service
spec:
  type: LoadBalancer
  selector:
    app: testapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
