name: "Test Deployment"
on:
  push:
    branches:
      - "main"
jobs:
  staging_deploy:
    name: "Test Deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      - run: ls -la
      - run: uname -a

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.5.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Authenticate Docker with Private Registry
      - run: doctl registry login --expiry-seconds 1800
      
      - name: Build Image
      - run: docker build . --file=Dockerfile --tag registry.digitalocean.com/ecommerce2022/ecommerce:latest
      - run: docker push registry.digitalocean.com/ecommerce2022/ecommerce:latest
